### ISSUE TITLE
MobileCore.trackAction() & MobileCore.trackState() not working

### ISSUE THREAD

**Issue by javiroll93** [dangermouse007/v5-aep-sdk-partner-demo#1]
Hi have been testing the Android sample to know how this new version of the SDK works and I can't see any HTTP request(hit) to Adobe servers. The only function that is sending hits it's the Adobe Target extension.

**Comment by dangermouse007** [comment]
Hi, I just added a dedicated launch config for the Android version so you can test it ootb. Usually you would have to create your own config in Adobe Launch to point to your Analytics and Target setup. You should now be able to see the Analytics calls in the log or network analyzer.

**Comment by javiroll93** [comment]
I tried with my own Adobe Launch config, but it didn't work. I will try it again. 
Thanks.

**Comment by javiroll93** [comment]
Hello again! I have tried the app without any modification but nothing changes. The "trackState" and the "trackAction" still not sending any hit to Adobe Server.

**Comment by javiroll93** [comment]
Ignore my last comment. I think that it was a cache problem. Now, with my Launch config is working.

**Comment by dangermouse007** [comment]
Great that you got it working!
