### ISSUE TITLE
Database error when change to another Activity

### ISSUE THREAD

**Issue by javiroll93** [dangermouse007/v5-aep-sdk-partner-demo#2]
I have noticed that if you click on "Send" button going to the "DisplayMessageActivity" and then you turn back to the "MainActivity", an error occurs.

The error is related with AdobeExperienceSDK.
Following I will put the error message:

_04-05 13:31:58.347 32203-32248/v5mobile.pma.eiselsbe.com.v5mobile E/SQLiteDatabase: Error inserting AAMFORWARDING=true OFFLINETRACKING=true ISPLACEHOLDER=false TIMESTAMP=1554463918 ISWAITING=false URL=ndh=1&ce=UTF-8&ts=1554463918&c.&a.&DeviceName=Aquaris%20M10&OSVersion=Android%206.0&RunMode=Application&Resolution=800x1232&AppID=v5mobile%201.0%20%281%29&.a&.c&t=00%2F00%2F0000%2000%3A00%3A00%200%20-120&mid=33424569006103796669216905509439111766&pageName=State&cp=foreground SERVER=https://maxeiselsberger.sc.omtrdc.net/b/ss/geo1pmav5mobile/10/JAVA-1.1.1-1.2.1-AN/s
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:789)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1501)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1371)
        at com.adobe.marketing.mobile.AndroidDatabase.insert(AndroidDatabase.java:159)
        at com.adobe.marketing.mobile.HitQueue.queue(HitQueue.java:166)
        at com.adobe.marketing.mobile.AnalyticsHitsDatabase.queue(AnalyticsHitsDatabase.java:251)
        at com.adobe.marketing.mobile.AnalyticsExtension.track(AnalyticsExtension.java:190)
        at com.adobe.marketing.mobile.AnalyticsExtension.process(AnalyticsExtension.java:871)
        at com.adobe.marketing.mobile.AnalyticsExtension.processEvents(AnalyticsExtension.java:797)
        at com.adobe.marketing.mobile.AnalyticsExtension.handleAnalyticsRequestEvent(AnalyticsExtension.java:1190)
        at com.adobe.marketing.mobile.AnalyticsListenerGenericTrackRequestContent$1.run(AnalyticsListenerGenericTrackRequestContent.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
04-05 13:31:58.348 32203-32248/v5mobile.pma.eiselsbe.com.v5mobile E/AdobeExperienceSDK: HitQueue - A database error occurred preventing a hit from being inserted
04-05 13:31:58.348 32203-32248/v5mobile.pma.eiselsbe.com.v5mobile E/AdobeExperienceSDK: HitsDatabase - Database in unrecoverable state, resetting._

**Comment by javiroll93** [comment]
To solve the issue, it's necessary to implement an _Application_ class and initialice the SDK there. The other way to solve the issue is modifying the AndroidManifest.xml making the _MainActivity_ with _launchMode="singleTop"_.

The problem is that the SDK not allow the application to call the "registerExtension" function multiple times and when that occurs, the SDK can be unstable and the DB files turns on _read only_ mode.

**First method:**
Create a new .java file with the following code:
```
package v5mobile.pma.eiselsbe.com.v5mobile;

import android.app.Application;
import android.util.Log;

import com.adobe.marketing.mobile.AdobeCallback;
import com.adobe.marketing.mobile.Analytics;
import com.adobe.marketing.mobile.Identity;
import com.adobe.marketing.mobile.InvalidInitException;
import com.adobe.marketing.mobile.Lifecycle;
import com.adobe.marketing.mobile.LoggingMode;
import com.adobe.marketing.mobile.MobileCore;
import com.adobe.marketing.mobile.Signal;
import com.adobe.marketing.mobile.UserProfile;

public class AbobeSDKInitialization extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        Log.wtf("SDK initialization message", "onCreate: Adobe DK Initialization starts...", null);
        MobileCore.setApplication(this);
        MobileCore.setLogLevel(LoggingMode.DEBUG);

        try {
            Analytics.registerExtension();
            UserProfile.registerExtension();
            Identity.registerExtension();
            Lifecycle.registerExtension();
            Signal.registerExtension();
            MobileCore.start(new AdobeCallback() {
                @Override
                public void call(Object o) {
                    MobileCore.configureWithAppID("launch-FAKELAUNCHID12345CHANGEIT");
                    //                    //MobileCore.configureWithFileInPath("/src/main/res/adobe_config.json");
                }
            });
        } catch (InvalidInitException e) {

        }
    }
}
```
Then, declare it on the _AndroidManifest.xml_:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="v5mobile.pma.eiselsbe.com.v5mobile">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application
        **android:name=".AbobeSDKInitialization"**
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".DisplayMessageActivity" android:parentActivityName=".MainActivity">
            <meta-data android:name="android.support.PARENT_ACTIVITY" android:value=".MainActivity" />
        </activity>
    </application>
</manifest>
```

**Second method:**
This is the simplest ones. Just change the _AndroidManifest.xml_ to this:
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="v5mobile.pma.eiselsbe.com.v5mobile">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity" **android:launchMode="singleTop"**>
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".DisplayMessageActivity" android:parentActivityName=".MainActivity">
            <meta-data android:name="android.support.PARENT_ACTIVITY" android:value=".MainActivity" />
        </activity>
    </application>
</manifest>
```

**Comment by dangermouse007** [comment]
Thanks for your great feedback and sorry it took me so long to reply and fix this!
